### ISSUE TITLE
更新内核后cat: /root/hy3/neko.txt: No such file or directory 

### ISSUE THREAD

**Issue by fuzhengqu** [seagullz4/hysteria2#12]
开发者，您好。我本来是用的好好的，今天执行脚本，选择了5更新内核，更新后，再次选择3查看配置出现此问题。发现原来导入到NekoBox中的hy2节点还是可以正常使用的。您给看下这个是啥问题。另外看到更新后版本还是显示23.12.03，和之前版本一致，没有变化，而不是Release中最新版本23.12.03.04.53
![1](https://github.com/seagullz4/hysteria2/assets/5155534/5cfdf519-488f-4b12-9fac-dea80909841d)

**Comment by seagullz4** [comment]
没事，重装一下就行

**Comment by fuzhengqu** [comment]
> 没事，重装一下就行

我卸载重装了下，现在无法正常使用了，提示端口有问题，您给看下啥问题，之前也大概是这些端口是没问题的，我看也都在要求的范围内
![2](https://github.com/seagullz4/hysteria2/assets/5155534/d033a9c1-052d-417f-9482-aac1a5cfebbe)

**Comment by seagullz4** [comment]
> > 没事，重装一下就行
> 
> 我卸载重装了下，现在无法正常使用了，提示端口有问题，您给看下啥问题，之前也大概是这些端口是没问题的，我看也都在要求的范围内
> ![2](https://github.com/seagullz4/hysteria2/assets/5155534/d033a9c1-052d-417f-9482-aac1a5cfebbe)
> 

端口跳跃电脑版是有bug的，我晚上回去改一下，手机端正常使用，你可以手动调节一下

**Comment by seagullz4** [comment]
> > 没事，重装一下就行
> 
> 我卸载重装了下，现在无法正常使用了，提示端口有问题，您给看下啥问题，之前也大概是这些端口是没问题的，我看也都在要求的范围内
> ![2](https://github.com/seagullz4/hysteria2/assets/5155534/d033a9c1-052d-417f-9482-aac1a5cfebbe)
> 

看看现在能不能在电脑端使用端口跳跃

**Comment by fuzhengqu** [comment]
> > > 没事，重装一下就行
> > 
> > 
> > 我卸载重装了下，现在无法正常使用了，提示端口有问题，您给看下啥问题，之前也大概是这些端口是没问题的，我看也都在要求的范围内
> > ![2](https://private-user-images.githubusercontent.com/5155534/289787242-d033a9c1-052d-417f-9482-aac1a5cfebbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzkxMzQsIm5iZiI6MTcwMjQzODgzNCwicGF0aCI6Ii81MTU1NTM0LzI4OTc4NzI0Mi1kMDMzYTljMS0wNTJkLTQxN2YtOTQ4Mi1hYWMxYTVjZmViYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDM0MDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVmNTg2MjBhN2Q4MmEwMzIzMDkxMWQzNjA2ZTVmYTU4Y2VhZGQwOWE5YWYzNWI2ZTk2NTYxN2I1OGMzNDhkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Mg8j-Y1VT0z-JYLMTSbabxblDb6-JMOjLPCa2nVm-2k)
> 
> 看看现在能不能在电脑端使用端口跳跃

已经可以了，谢谢
