### ISSUE TITLE
脚本检测端口的时候，将tcp的端口也一并检查了

### ISSUE THREAD

**Issue by linsongze** [seagullz4/hysteria2#13]
netstat -tuln 会将tcp的端口也列出来，但是hy2应该只使用udp的端口就足够了。

**Comment by kettly1260** [comment]
> > netstat -tuln 会将tcp的端口也列出来，但是hy2应该只使用udp的端口就足够了。
> 
> 没事,保险一点,防止bug🐾🐾🐾

但是这样会影响其他比如nginx的使用
