### ISSUE TITLE
请求大佬加上端口跳跃功能，家宽封得太厉害了

### ISSUE THREAD

**Issue by msn1983aa** [seagullz4/hysteria2#14]
hy2的原作者是这样描述端口跳跃的：
端口跳跃
中国用户有时报告运营商会阻断或限速 UDP 连接。不过，这些限制往往仅限单个端口。端口跳跃可用作此情况的解决方法。

https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/#_3

请求大佬在百忙中在脚本里加一下这个功能

**Comment by seagullz4** [comment]
好像有端口跳跃功能吧😭

**Comment by msn1983aa** [comment]
> 好像有端口跳跃功能吧😭仔细看看

我瞎了，谢谢大佬！

**Comment by Grey0520** [comment]
原来如此，我还说为啥我配置了100次都不对，原来是运营商这个老登
