### ISSUE TITLE
端口跳跃的iptables 配置问题

### ISSUE THREAD

**Issue by WenLiCG** [seagullz4/hysteria2#15]
你好
我在配置hysteria2的时候选择了端口跳跃,按照官网的要求需要使用iptables转发端口.
但是我发现脚本没有设置iptables规则哈(iptables -L查看的),想问一下脚本是怎么实现端口跳跃的哈? 还是官网的iptables配置是可选项哈?
https://v2.hysteria.network/zh/docs/advanced/Port-Hopping/
感谢

**Comment by seagullz4** [comment]
看这里,老大哥————[🐶🐶](https://github.com/seagullz4/hysteria2/blob/main/install.sh#L553-L567)
