### ISSUE TITLE
不支持端口跳跃

### ISSUE THREAD

**Issue by UncleUncleWang** [seagullz4/hysteria2#2]
rt

**Comment by seagullz4** [comment]
晚上加上，主要是nekobox手机端不支持端口跳跃💥

**Comment by seagullz4** [comment]
已添加端口跳跃功能**😇**

**Comment by UncleUncleWang** [comment]
> 已添加端口跳跃功能**😇**

安装步骤里面确实有端口跳跃了，生成的节点链接里面没有体现啊......略显潦草了

**Comment by seagullz4** [comment]
忘记了，你先暂时自己去开启，晚上我添加上去😴😴😴

**Comment by eightsheep67** [comment]
哦是还没有正常开启呀。。。等晚上更新

**Comment by seagullz4** [comment]
> 哦是还没有正常开启呀。。。等晚上更新

端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些

**Comment by eightsheep67** [comment]
> > 哦是还没有正常开启呀。。。等晚上更新
> 
> 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些

不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。

**Comment by seagullz4** [comment]
> > > 哦是还没有正常开启呀。。。等晚上更新
> > 
> > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> 
> 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。

我不大清楚，可能是系统适配原因，可能你的系统不支持iptables的转发吧，我试了一下，我使用777作为主端口，将8888-9999直接作为范围端口，我使用8888-9999之间的任意端口是可以将UDP流量转发到777主端口的，可以正常连接使用

**Comment by seagullz4** [comment]
> > > 哦是还没有正常开启呀。。。等晚上更新
> > 
> > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> 
> 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。

还是推荐你使用ubuntu都系统，我的这些脚本都是根据这个系统适配的😇

**Comment by eightsheep67** [comment]
> > > > 哦是还没有正常开启呀。。。等晚上更新
> > > 
> > > 
> > > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> > 
> > 
> > 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> > 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> > 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。
> 
> 还是推荐你使用ubuntu都系统，我的这些脚本都是根据这个系统适配的😇

我是ubuntu呀，甲骨文的vps，20.04.6 LTS，我也已经把用了以下命令了
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F

**Comment by eightsheep67** [comment]
> > > > > > 哦是还没有正常开启呀。。。等晚上更新
> > > > > 
> > > > > 
> > > > > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> > > > 
> > > > 
> > > > 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> > > > 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> > > > 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。
> > > 
> > > 
> > > 还是推荐你使用ubuntu都系统，我的这些脚本都是根据这个系统适配的😇
> > 
> > 
> > 我是ubuntu呀，甲骨文的vps，20.04.6 LTS，我也已经把用了以下命令了
> > iptables -P INPUT ACCEPT
> > iptables -P FORWARD ACCEPT
> > iptables -P OUTPUT ACCEPT
> > iptables -F
> 
> 没看懂，如果你想用的是端口跳跃，没必要执行你的那些命令，直接在脚本中选择就行💔，我刚才用自己的两台不同厂商的vps试了一下，完全OK的 不需要你有多余的配置😅，甲骨文的好像是arm的架构，我没太会研究😅

这些命令是把甲骨文的VPS端口全部放开，我的VPS都是X86的。

**Comment by seagullz4** [comment]
> > > > > > > 哦是还没有正常开启呀。。。等晚上更新
> > > > > > 
> > > > > > 
> > > > > > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> > > > > 
> > > > > 
> > > > > 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> > > > > 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> > > > > 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。
> > > > 
> > > > 
> > > > 还是推荐你使用ubuntu都系统，我的这些脚本都是根据这个系统适配的😇
> > > 
> > > 
> > > 我是ubuntu呀，甲骨文的vps，20.04.6 LTS，我也已经把用了以下命令了
> > > iptables -P INPUT ACCEPT
> > > iptables -P FORWARD ACCEPT
> > > iptables -P OUTPUT ACCEPT
> > > iptables -F
> > 
> > 没看懂，如果你想用的是端口跳跃，没必要执行你的那些命令，直接在脚本中选择就行💔，我刚才用自己的两台不同厂商的vps试了一下，完全OK的 不需要你有多余的配置😅，甲骨文的好像是arm的架构，我没太会研究😅
> 
> 这些命令是把甲骨文的VPS端口全部放开，我的VPS都是X86的。

`iptables -F` 是一个Linux命令，用于清空（flush）iptables防火墙规则。具体来说，它会删除所有已经定义的防火墙规则，包括所有的链（chains）和规则，将防火墙恢复到默认配置。

**Comment by eightsheep67** [comment]
> > > > > > > > 哦是还没有正常开启呀。。。等晚上更新
> > > > > > > 
> > > > > > > 
> > > > > > > 端口跳跃是开启了可以正常使用的，就是没有在节点信息中显示，晚上我加上，推荐ubuntu的服务器好些
> > > > > > 
> > > > > > 
> > > > > > 不是设置了端口跳跃后，我任意挑一个端口当普通端口设置都可以连接吗？
> > > > > > 现在openclash还不支持hy2的端口跳跃，我先自己配置一堆不同端口的相同节点来使用。
> > > > > > 但是发现只有第一个设置的那个端口可以连接，后面端口跳跃范围里的端口都不能用。
> > > > > 
> > > > > 
> > > > > 还是推荐你使用ubuntu都系统，我的这些脚本都是根据这个系统适配的😇
> > > > 
> > > > 
> > > > 我是ubuntu呀，甲骨文的vps，20.04.6 LTS，我也已经把用了以下命令了
> > > > iptables -P INPUT ACCEPT
> > > > iptables -P FORWARD ACCEPT
> > > > iptables -P OUTPUT ACCEPT
> > > > iptables -F
> > > 
> > > 
> > > 没看懂，如果你想用的是端口跳跃，没必要执行你的那些命令，直接在脚本中选择就行💔，我刚才用自己的两台不同厂商的vps试了一下，完全OK的 不需要你有多余的配置😅，甲骨文的好像是arm的架构，我没太会研究😅
> > 
> > 
> > 这些命令是把甲骨文的VPS端口全部放开，我的VPS都是X86的。
> 
> `iptables -F` 是一个Linux命令，用于清空（flush）iptables防火墙规则。具体来说，它会删除所有已经定义的防火墙规则，包括所有的链（chains）和规则，将防火墙恢复到默认配置。

原来如此，这个命令以前在搭建vless的时候使用，那我现在纯hy，我重启后重新搭建一次试试看
