### ISSUE TITLE
安装结束，好像服务没有正常启动，还请抽空看看。

### ISSUE THREAD

**Issue by punkzhang** [seagullz4/hysteria2#25]
root@e4-240702:~# systemctl status hysteria.service
● hysteria.service - My Hysteria Server
     Loaded: loaded (/etc/systemd/system/hysteria.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-07-06 08:23:30 UTC; 12s ago
    Process: 4577 ExecStart=/root/hy3/hysteria-linux-arm64 server (code=exited, status=1/FAILURE)
   Main PID: 4577 (code=exited, status=1/FAILURE)

Jul 06 08:23:30 e4-240702 systemd[1]: hysteria.service: Scheduled restart job, restart counter is at 5.
Jul 06 08:23:30 e4-240702 systemd[1]: Stopped My Hysteria Server.
Jul 06 08:23:30 e4-240702 systemd[1]: hysteria.service: Start request repeated too quickly.
Jul 06 08:23:30 e4-240702 systemd[1]: hysteria.service: Failed with result 'exit-code'.
Jul 06 08:23:30 e4-240702 systemd[1]: Failed to start My Hysteria Server.

**Comment by seagullz4** [comment]
什么服务器

**Comment by punkzhang** [comment]
甲骨文云。之前用的也是你的这个脚本，没有问题。今天部署了好像起不来了。

**Comment by seagullz4** [comment]
> 甲骨文云。之前用的也是你的这个脚本，没有问题。今天部署了好像起不来了。

昨天才同意了别人拉去的合并请求，我也不知道有没有bug，晚上我慢慢看

**Comment by punkzhang** [comment]
> > 甲骨文云。之前用的也是你的这个脚本，没有问题。今天部署了好像起不来了。
> 
> 你先卸载脚本在装过，看能不能行

OK，明天我再部署一下。届时反馈。

**Comment by punkzhang** [comment]
早上测了一下，还是有问题，说明一下情况：
刚部署完，显示跟之前一样Fail了，还是hysteria.service: Start request repeated too quickly.
等了一会，重启了服务器，hysteria.service跑起来了。但是连不上。
不知道是不是CA证书那边的问题。
我用的是acme的证书，域名已经映射在该服务器上，cloudflare的解析。
我也找了一下，服务器上确实没找到CA证书。
我也不清楚，Hysteria是否需要装个nginx，才能运行。

**Comment by punkzhang** [comment]
hy3下面没有CA目录。
root@e4-240702:~/hy3# ls
acme
clash-mate.yaml
config.yaml
hysteria-linux-arm64
ipppp.sh
neko.txt
nohup.out
倒是acme里面有
root@e4-240702:~/hy3/acme/certificates/acme-v02.api.letsencrypt.org-directory/oracle.634605.xyz# ls
oracle.634605.xyz.crt
oracle.634605.xyz.json
oracle.634605.xyz.key

**Comment by seagullz4** [comment]
> hy3下面没有CA目录。
> root@e4-240702:~/hy3# ls
> acme
> clash-mate.yaml
> config.yaml
> hysteria-linux-arm64
> ipppp.sh
> neko.txt
> nohup.out
> 倒是acme里面有
> root@e4-240702:~/hy3/acme/certificates/acme-v02.api.letsencrypt.org-directory/oracle.634605.xyz# ls
> oracle.634605.xyz.crt
> oracle.634605.xyz.json
> oracle.634605.xyz.key
> 

尝试自签证书试一下，自签没问题就应该是acme签证书签多了，第二天就好了

**Comment by punkzhang** [comment]
又部署了一遍，自签的，还是连不上。
安装结束后service都起不来，重启之后能起来，但是连不上。
不知道是不是我自己的问题。我保持关注这个项目吧。
