### ISSUE TITLE
关于证书申请的建议

### ISSUE THREAD

**Issue by zhecydn** [seagullz4/hysteria2#26]
大佬你好，我在使用您的一键安装脚本时发现hy2安装后无法运行，检查了一下hy2的配置文件后发现是域名和证书那里有问题 failed to load server config        {"error": "invalid config: acme.domains: 我的域名: obtaining certificate，由于我使用的不是80/443端口，因此大概率是证书没有申请成功，最终使用您的一键脚本部署失败
在我的查找之后，我发现这个问题在hy2的官方文档中给出了解决方案
https://v2.hysteria.network/zh/docs/advanced/ACME-DNS-Config/
我使用了官方的一键脚本并尝试修改了配置文件，由于我用的cloudflare托管域名，所以我在配置文件中加了下面这一段，并修改了我自己的域名和其他cloudflare账户信息，最终成功部署

acme:
  domains:
    - "*.example.com"
  email: your@email.address
  type: dns
  dns:
    name: cloudflare
    config:
      cloudflare_api_token: Dxabckw9dB_jYBdi89kgyaS8wRjqqSsd679urScKOBP

希望您的一键脚本在申请证书的时候针对非80/443端口证书申请也能够加上这部分的参数选择

**Comment by zhecydn** [comment]
在查看了这个项目前面的人提出的issue时，我也发现了有人和我是一样的问题，说明这个问题应该不是个例

**Comment by seagullz4** [comment]
> 在查看了这个项目前面的人提出的issue时，我也发现了有人和我是一样的问题，说明这个问题应该不是个例

给个TG联系方式谢谢

**Comment by seagullz4** [comment]
这两天我会进行修改优化，谢谢建议

**Comment by seagullz4** [comment]
TG联系我一下 @seagullz44
