### ISSUE TITLE
搭建成功但实际无法使用

### ISSUE THREAD

**Issue by villager10115** [seagullz4/hysteria2#31]
已经验证：域名
域名效果：ping时能ping到自己的vps主机ipv4
操作步骤：
-添加无小黄云ipv4dns解析
-添加了有小黄云的ipv6解析
-安装脚本
-一路除了域名和令牌邮箱外默认搭建
-在v2rayn上测试
结果：-1ms，实际使用无法访问墙外任何网站

**Comment by seagullz4** [comment]
明天有空看看哈~~~~

**Comment by JamieBox2020** [comment]
我按照脚本一路执行下去没有问题，用的也是自己域名的AC证书，能正常使用；
但是为啥输入hy2快捷指令不能快速启动脚本，控制台报错如下：
`root@JamieHost:~# hy2
-bash: /usr/local/bin/hy2: No such file or directory`
如果楼主有空也帮我看一下~~

**Comment by seagullz4** [comment]
我这边没试过 v2ray 推荐使用hiddify或者nekoray
