### ISSUE TITLE
安装完成了，该怎么用呀？小白不会

### ISSUE THREAD

**Issue by zhouta0** [seagullz4/hysteria2#32]
脚本运行后有很多选择，不会用呀，一直回车后，提示安装成功。
然后该做啥，也不会呀。
hidify，v2rayN不知道该怎么配置，能出小白教程吗？

**Comment by seagullz4** [comment]
剪贴板导入

**Comment by lijusjy** [comment]
自行谷歌一下


seagullz4 ***@***.***>于2024年11月13日 周三22:01写道：

**Comment by lijusjy** [comment]
复制粘贴hysteria2后面的节点信息到v2rayn

cai chen ***@***.***>于2024年11月13日 周三22:24写道：
