### ISSUE TITLE
最新版2.6.0版本安装后显示未运行

### ISSUE THREAD

**Issue by fuzhengqu** [seagullz4/hysteria2#33]
上个版本安装后是正常的，更新后显示未运行。卸载重新安装2.6也不行

**Comment by seagullz4** [comment]
稍等哈我这边测试一下

**Comment by seagullz4** [comment]
我这边测试一切正常的，麻烦说一下你的详细过程这些

**Comment by fuzhengqu** [comment]
我使用的是ubuntu24.04 server，使用最新的一键脚本执行，中间过程没有报错，选择的我自己已经解析到这个服务器IP的域名。
![1](https://github.com/user-attachments/assets/577b04e2-5384-4b67-8bda-7a0c364589a1)
![2](https://github.com/user-attachments/assets/2b12d4c6-8daf-4a15-b5aa-91c7f5f7b69a)
![3](https://github.com/user-attachments/assets/a4a89bdf-caa1-456a-ac25-39120c61650f)
![4](https://github.com/user-attachments/assets/6be1f00b-c6b5-4f8d-b2ce-3c272aa8a1e7)
![安装后](https://github.com/user-attachments/assets/12703853-b9e0-4b31-baaa-7826ec3db784)

**Comment by seagullz4** [comment]
实际测试也不能连接对吧

**Comment by fuzhengqu** [comment]
> 实际测试也不能连接对吧

是的
