### ISSUE TITLE
端口跳跃无法使用

### ISSUE THREAD

**Issue by feimeng2017** [seagullz4/hysteria2#6]
配置好服务端   复制节点信息到nekobox   无法使用  nekobox是最新版3.24内核使用sing-box    hysteria2也是2.2的最新版    删除nekobox节点配置里面的端口跳跃栏里面的数据留空    不使用   节点是可以使用的    

请问下这是怎么回事？？？

VPS是重装之后  没装任何东西  就安装了warp  我是v6机

**Comment by seagullz4** [comment]
安装最新版nekobox,目前版本1.2.9,vps推荐ubuntu

**Comment by seagullz4** [comment]
电脑端暂时等待更新,你可以手动配置端口跳跃,我这个节点信息是适用于手机端的，后续会应该会增加电脑端配置,主要是端口跳跃感觉不是很多人需要

**Comment by feimeng2017** [comment]
好的  辛苦了  刚开始在公司用的HY2没事  挺好  很快    但是发现家里的网络不行  好像是被qos了  速度简直不能用  所以想试试端口跳跃功能      还有一点用别人的脚本YouTube跑4万左右    用你的能跑6-8万    很惊喜啊      下次更新希望能加上   感谢！！！

**Comment by seagullz4** [comment]
周末将会对电脑端端口跳跃补齐
