### ISSUE TITLE
增加一个核心在线更新的功能吧，兄弟

### ISSUE THREAD

**Issue by UncleUncleWang** [seagullz4/hysteria2#7]
rt

**Comment by seagullz4** [comment]
收到,宝子明天马上安排自动更新版本

**Comment by UncleUncleWang** [comment]
> 收到,宝子明天马上安排自动更新版本

生产队的大鹅都没这么快

**Comment by seagullz4** [comment]
OK了，增加了在线更新功能，其实写了两个版本，一个是自动更新，一个是现在这个在线更新，但想了一下，自动更新有点太占CPU了，而且有多重原因可能导致识别，所以就只更新了在线更新功能
